<?php

namespace App\Tests\Unit\Entity;

use App\Entity\Avatar;
use App\Entity\User;
use PHPUnit\Framework\TestCase;

class AvatarTest extends TestCase
{
    private Avatar $avatar;

    protected function setUp(): void
    {
        parent::setUp();
        $this->avatar = new Avatar();
    }

    /**
     * Test if the ID is initially null for a new entity.
     * IDs are typically generated by the database upon persistence.
     */
    public function testGetId(): void
    {
        $this->assertNull($this->avatar->getId());
    }

    /**
     * Test setting and getting the associated User.
     */
    public function testUserGetAndSet(): void
    {
        $this->assertNull($this->avatar->getUser());

        $userMock = $this->createMock(User::class);

        $this->avatar->setUser($userMock);

        $this->assertSame($userMock, $this->avatar->getUser());

        $this->avatar->setUser(null);
        $this->assertNull($this->avatar->getUser());
    }

    /**
     * Test setting and getting the filename.
     */
    public function testFilenameGetAndSet(): void
    {
        $filename = 'my_avatar.jpg';
        $this->avatar->setFilename($filename);

        $this->assertEquals($filename, $this->avatar->getFilename());
        $this->assertIsString($this->avatar->getFilename());

        $this->avatar->setFilename(null);
        $this->assertNull($this->avatar->getFilename());
    }
}
