<?php

namespace App\Tests\Unit\Entity;

use App\Entity\Avatar;
use App\Entity\User; // Assuming User entity exists and is used in Avatar
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

class AvatarTest extends TestCase
{
    private Avatar $avatar;

    protected function setUp(): void
    {
        // Call the parent setUp method to ensure proper test case initialization
        parent::setUp();
        // Create a new Avatar instance before each test
        $this->avatar = new Avatar();
    }

    /**
     * Test if the ID is initially null for a new entity.
     * IDs are typically generated by the database upon persistence.
     */
    public function testGetId(): void
    {
        $this->assertNull($this->avatar->getId());
    }

    /**
     * Test setting and getting the associated User.
     */
    public function testUserGetAndSet(): void
    {
        // Initial state: user should be null
        $this->assertNull($this->avatar->getUser());

        // Create a mock User object
        $userMock = $this->createMock(User::class);

        // Set the user on the avatar
        $this->avatar->setUser($userMock);

        // Verify that the user is correctly set and retrieved
        $this->assertSame($userMock, $this->avatar->getUser());

        // Test setting user to null
        $this->avatar->setUser(null);
        $this->assertNull($this->avatar->getUser());
    }

    /**
     * Test setting and getting the filename.
     */
    public function testFilenameGetAndSet(): void
    {
        $filename = 'my_avatar.jpg';
        $this->avatar->setFilename($filename);

        // Verify that the filename is correctly set and retrieved
        $this->assertEquals($filename, $this->avatar->getFilename());
        $this->assertIsString($this->avatar->getFilename());

        // Test setting filename to null
        $this->avatar->setFilename(null);
        $this->assertNull($this->avatar->getFilename());
    }
}
