<?php

namespace App\Tests\Unit\Entity;

use App\Entity\Category;
use PHPUnit\Framework\TestCase;

class CategoryTest extends TestCase
{
    private Category $category;

    protected function setUp(): void
    {
        parent::setUp();
        $this->category = new Category();
    }

    /**
     * Test if the ID is initially null for a new entity.
     * IDs are typically generated by the database upon persistence.
     */
    public function testGetId(): void
    {
        $this->assertNull($this->category->getId());
    }

    /**
     * Test setting and getting the title.
     */
    public function testTitleGetAndSet(): void
    {
        $title = 'Test Category Title';
        $this->category->setTitle($title);

        $this->assertEquals($title, $this->category->getTitle());
        $this->assertIsString($this->category->getTitle());

        $this->category->setTitle(null);
        $this->assertNull($this->category->getTitle());
    }

    /**
     * Test setting and getting the createdAt timestamp.
     */
    public function testCreatedAtGetAndSet(): void
    {
        $dateTime = new \DateTimeImmutable('2023-01-15 10:00:00');
        $this->category->setCreatedAt($dateTime);

        $this->assertEquals($dateTime, $this->category->getCreatedAt());
        $this->assertInstanceOf(\DateTimeImmutable::class, $this->category->getCreatedAt());

        $this->category->setCreatedAt(null);
        $this->assertNull($this->category->getCreatedAt());
    }

    /**
     * Test setting and getting the updatedAt timestamp.
     */
    public function testUpdatedAtGetAndSet(): void
    {
        $dateTime = new \DateTimeImmutable('2023-01-15 11:30:00');
        $this->category->setUpdatedAt($dateTime);

        $this->assertEquals($dateTime, $this->category->getUpdatedAt());
        $this->assertInstanceOf(\DateTimeImmutable::class, $this->category->getUpdatedAt());

        // Test setting to null
        $this->category->setUpdatedAt(null);
        $this->assertNull($this->category->getUpdatedAt());
    }

    /**
     * Test setting and getting the slug.
     */
    public function testSlugGetAndSet(): void
    {
        $slug = 'test-category-slug';
        $result = $this->category->setSlug($slug);

        $this->assertEquals($slug, $this->category->getSlug());
        $this->assertIsString($this->category->getSlug());
        $this->assertSame($this->category, $result);
    }
}
