<?php

namespace App\Tests\Unit\Entity;

use App\Entity\Enum\UserRole; // Assuming this enum exists and is used
use App\Entity\User;
use App\Entity\Avatar; // For testing the Avatar relation
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

class UserTest extends TestCase
{
    private User $user;

    protected function setUp(): void
    {
        // Call the parent setUp method to ensure proper test case initialization
        parent::setUp();
        // Create a new User instance before each test
        $this->user = new User();
    }

    /**
     * Test if the ID is initially null for a new entity.
     * IDs are typically generated by the database upon persistence.
     */
    public function testGetId(): void
    {
        $this->assertNull($this->user->getId());
    }

    /**
     * Test setting and getting the email address, and verify user identifier.
     */
    public function testEmailGetAndSet(): void
    {
        $email = 'test@example.com';
        $this->user->setEmail($email);

        // Verify that the email is correctly set and retrieved
        $this->assertEquals($email, $this->user->getEmail());
        // Verify that the user identifier is the email (as per UserInterface)
        $this->assertEquals($email, $this->user->getUserIdentifier());
    }

    /**
     * Test setting and getting roles, including default role behavior.
     */
    public function testRolesGetAndSet(): void
    {
        // 1. Test default role: User should always have ROLE_USER
        $this->assertEquals([UserRole::ROLE_USER->value], $this->user->getRoles());

        // 2. Test setting multiple roles
        $roles = [UserRole::ROLE_ADMIN->value, UserRole::ROLE_USER->value, 'ROLE_EDITOR'];
        $this->user->setRoles($roles);
        // Use assertEqualsCanonicalizing to ignore array order when comparing
        $this->assertEqualsCanonicalizing([UserRole::ROLE_ADMIN->value, UserRole::ROLE_USER->value, 'ROLE_EDITOR'], $this->user->getRoles());

        // 3. Test that ROLE_USER is automatically added if not explicitly present
        $this->user->setRoles(['ROLE_MANAGER']);
        // FIX: Corrected syntax for 'ROLE_MANAGER' as it's not part of the UserRole enum
        // and fixed the concatenation operator from '.' to '->' if it were an enum case.
        $this->assertEqualsCanonicalizing(['ROLE_MANAGER', UserRole::ROLE_USER->value], $this->user->getRoles());

        // 4. Test that ROLE_USER is not duplicated if already present
        $this->user->setRoles([UserRole::ROLE_USER->value, 'ROLE_MANAGER']);
        $this->assertEqualsCanonicalizing([UserRole::ROLE_USER->value, 'ROLE_MANAGER'], $this->user->getRoles());

        // 5. Test setting an empty array of roles - should still result in ROLE_USER
        $this->user->setRoles([]);
        $this->assertEquals([UserRole::ROLE_USER->value], $this->user->getRoles());
    }

    /**
     * Test setting and getting the password.
     */
    public function testPasswordGetAndSet(): void
    {
        $password = 'hashed_secure_password_string';
        $this->user->setPassword($password);

        // Verify that the password is correctly set and retrieved
        $this->assertEquals($password, $this->user->getPassword());
    }

    /**
     * Test the eraseCredentials method, ensuring it clears the password.
     */
    public function testEraseCredentials(): void
    {
        $this->user->setPassword('some_temporary_password');
        $this->assertNotNull($this->user->getPassword()); // Ensure it's set before erasing

        $this->user->eraseCredentials();
        // This assertion expects the password to be null after erasing credentials.
        // If this test fails, please verify that the eraseCredentials() method in your User entity
        // (App\Entity\User.php) actually sets the $password property to null (e.g., $this->password = null;).
        // The current test logic is correct for the intended behavior of eraseCredentials.
        $this->assertNull($this->user->getPassword());
    }

    /**
     * Test setting and getting the first name.
     */
    public function testFirstNameGetAndSet(): void
    {
        $firstName = 'John';
        $this->user->setFirstName($firstName);

        $this->assertEquals($firstName, $this->user->getFirstName());
        $this->assertIsString($this->user->getFirstName());

        // Test setting null
        $this->user->setFirstName(null);
        $this->assertNull($this->user->getFirstName());
    }

    /**
     * Test setting and getting the last name.
     */
    public function testLastNameGetAndSet(): void
    {
        $lastName = 'Doe';
        $this->user->setLastName($lastName);

        $this->assertEquals($lastName, $this->user->getLastName());
        $this->assertIsString($this->user->getLastName());

        // Test setting null
        $this->user->setLastName(null);
        $this->assertNull($this->user->getLastName());
    }

    /**
     * Test setting and getting the isBlocked status.
     */
    public function testIsBlockedGetAndSet(): void
    {
        // Default value should be false (as defined in the entity)
        $this->assertFalse($this->user->getIsBlocked());

        // Test setting to true
        $this->user->setIsBlocked(true);
        $this->assertTrue($this->user->getIsBlocked());

        // Test setting back to false
        $this->user->setIsBlocked(false);
        $this->assertFalse($this->user->getIsBlocked());
    }

    /**
     * Test the Avatar relation's getter and setter, including bidirectional setup.
     */
    public function testAvatarGetAndSet(): void
    {
        // Initial state: avatar should be null
        $this->assertNull($this->user->getAvatar());

        // Create a mock Avatar object
        $avatarMock = $this->createMock(Avatar::class);

        // Expect setAvatar to be called on the avatar mock to establish the bidirectional relation
        $avatarMock->expects($this->once())
            ->method('getUser')
            ->willReturn(null); // Simulate avatar not yet having this user
        $avatarMock->expects($this->once())
            ->method('setUser')
            ->with($this->user); // Expect avatar to be linked back to this user

        // Set the avatar on the user
        $result = $this->user->setAvatar($avatarMock);

        // Verify that setAvatar returns the User instance (fluent interface)
        $this->assertSame($this->user, $result);
        // Verify that the user now has the avatar
        $this->assertSame($avatarMock, $this->user->getAvatar());
    }
}
