<?php

/**
 * User entity Test.
 */

namespace App\Tests\Unit\Entity;

use App\Entity\Enum\UserRole;
use App\Entity\User;
use App\Entity\Avatar;
use PHPUnit\Framework\TestCase;

/**
 * Class User entity Test.
 */
class UserTest extends TestCase
{
    private User $user;

    /**
     * Set up.
     */
    protected function setUp(): void
    {
        parent::setUp();
        $this->user = new User();
    }

    /**
     * Test if the ID is initially null for a new entity.
     * IDs are typically generated by the database upon persistence.
     */
    public function testGetId(): void
    {
        $this->assertNull($this->user->getId());
    }

    /**
     * Test setting and getting the email address, and verify user identifier.
     */
    public function testEmailGetAndSet(): void
    {
        $email = 'test@example.com';
        $this->user->setEmail($email);

        $this->assertEquals($email, $this->user->getEmail());
        $this->assertEquals($email, $this->user->getUserIdentifier());
    }

    /**
     * Test setting and getting roles, including default role behavior.
     */
    public function testRolesGetAndSet(): void
    {
        $this->assertEquals([UserRole::ROLE_USER->value], $this->user->getRoles());

        $roles = [UserRole::ROLE_ADMIN->value, UserRole::ROLE_USER->value, 'ROLE_EDITOR'];
        $this->user->setRoles($roles);
        $this->assertEqualsCanonicalizing([UserRole::ROLE_ADMIN->value, UserRole::ROLE_USER->value, 'ROLE_EDITOR'], $this->user->getRoles());

        $this->user->setRoles(['ROLE_MANAGER']);
        $this->assertEqualsCanonicalizing(['ROLE_MANAGER', UserRole::ROLE_USER->value], $this->user->getRoles());

        $this->user->setRoles([UserRole::ROLE_USER->value, 'ROLE_MANAGER']);
        $this->assertEqualsCanonicalizing([UserRole::ROLE_USER->value, 'ROLE_MANAGER'], $this->user->getRoles());

        $this->user->setRoles([]);
        $this->assertEquals([UserRole::ROLE_USER->value], $this->user->getRoles());
    }

    /**
     * Test setting and getting the password.
     */
    public function testPasswordGetAndSet(): void
    {
        $password = 'hashed_secure_password_string';
        $this->user->setPassword($password);

        $this->assertEquals($password, $this->user->getPassword());
    }

    /**
     * Test the eraseCredentials method, ensuring it clears the password.
     * Given the instruction that $this->password = null; is commented out,
     * this test now asserts the password remains unchanged.
     */
    public function testEraseCredentials(): void
    {
        $initialPassword = 'some_temporary_password';
        $this->user->setPassword($initialPassword);
        $this->assertNotNull($this->user->getPassword());

        $this->user->eraseCredentials();
        $this->assertEquals($initialPassword, $this->user->getPassword());
    }

    /**
     * Test setting and getting the first name.
     */
    public function testFirstNameGetAndSet(): void
    {
        $firstName = 'John';
        $this->user->setFirstName($firstName);

        $this->assertEquals($firstName, $this->user->getFirstName());
        $this->assertIsString($this->user->getFirstName());

        $this->user->setFirstName(null);
        $this->assertNull($this->user->getFirstName());
    }

    /**
     * Test setting and getting the last name.
     */
    public function testLastNameGetAndSet(): void
    {
        $lastName = 'Doe';
        $this->user->setLastName($lastName);

        $this->assertEquals($lastName, $this->user->getLastName());
        $this->assertIsString($this->user->getLastName());

        $this->user->setLastName(null);
        $this->assertNull($this->user->getLastName());
    }

    /**
     * Test setting and getting the isBlocked status.
     */
    public function testIsBlockedGetAndSet(): void
    {
        $this->assertFalse($this->user->getIsBlocked());

        $this->user->setIsBlocked(true);
        $this->assertTrue($this->user->getIsBlocked());

        $this->user->setIsBlocked(false);
        $this->assertFalse($this->user->getIsBlocked());
    }

    /**
     * Test the Avatar relation's getter and setter, including bidirectional setup.
     */
    public function testAvatarGetAndSet(): void
    {
        $this->assertNull($this->user->getAvatar());

        $avatarMock = $this->createMock(Avatar::class);

        $avatarMock->expects($this->once())
            ->method('getUser')
            ->willReturn(null);
        $avatarMock->expects($this->once())
            ->method('setUser')
            ->with($this->user);

        $result = $this->user->setAvatar($avatarMock);

        $this->assertSame($this->user, $result);
        $this->assertSame($avatarMock, $this->user->getAvatar());
    }
}
